{
  parserClass='io.yaochi.intellij.plugin.parser.TEALParser'

  psiClassPrefix='TEAL'
  psiImplClassSuffix='Impl'
  psiPackage='io.yaochi.intellij.plugin.psi'
  psiImplPackage='io.yaochi.intellij.plugin.psi.impl'
  psiImplUtilClass="io.yaochi.intellij.plugin.psi.impl.TEALPsiImplUtil"

  elementTypeHolderClass="io.yaochi.intellij.plugin.psi.TEALTypes"
  elementTypeClass="io.yaochi.intellij.plugin.psi.TEALElementType"
  tokenTypeClass="io.yaochi.intellij.plugin.psi.TEALTokenType"
}

